### ISSUE TITLE
Conversion to Dalvik format failed with error 1

### ISSUE THREAD

**Issue by HanderWei** [plutext/AndroidDocxToHtml#3]
I try to run this Android application,but it doesn't work.

The error is :Conversion to Dalvik format failed with error 1

Any help will be appreciate!

**Comment by neoxp** [comment]
**SOLUTIONS TO ERROR unable to dalvik 1 in eclipse AND SUN / MISC / BASECODER64 IN ECLISPE.**

INSTRUCTIONS TO SOLVE THE PROBLEM ARE:

1- INSTALL WINDOWS XP SP2 WITH JAVA 6.

2- DOWNLOAD ADT VERSION 23.0.2 WITH SDK 19.

3- DECOMPRESS THE ADT AND INSTALL IT ON YOUR COMPUTER.

4- OPEN THE ECLIPSE AS ADMINISTRATOR AND IMPORT THE ANDORID FILE.

5- IN THE FILE project.properties WRITE THIS -> target = android-19.

6- EXPORT YOUR PROJECT AND NO MORE THIS ERROR WILL APPEAR.

7- AND SO WE SOLVE THE ERROR CHECKED AND RUNNING.

8- 100% CHECKED BY ME.
